# This is a basic workflow to help you get started with Actions

name: Nodebrew Support Script CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['lts', 'stable', 'latest', '']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install nodebrew
      run: |
            curl -L git.io/nodebrew | perl - setup

    - name: Check Successfull Install nodebrew
      run: |
            export PATH=$HOME/.nodebrew/current/bin:$PATH
            source ~/.bashrc
            which nodebrew
    - name: Testing Args on ${{ matrix.version }}
      run: bash -x ./node_install.sh ${{ matrix.version }}
