# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI (Get Node Version)

on:
  schedule:
  - cron: '0 0 */1 * *'
  push:
    branches: [ master ]
    
jobs:
  get-version:
    name: get-version

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git remote set-url origin "https://Kazanami:${{secrets.GITHUB_TOKEN}}@github.com/Kazanami/git-action-test"
    - run: git config user.name "Github Action Runner"
    - run: git config user.email "github-action-runner@example.com"
    - run: npm i
    - run: node main.js
    - run: git add .
    - run: git commit -m "recursive run"
    - run: git push origin master
      env:
        CI: true
